### ISSUE TITLE
v0.2 md5 해시 라이브러리를 활용한 무결성 체크

### ISSUE THREAD

**Issue by sunmings** [hpk23/S.W_3team#10]
참고한 사이트 : http://bbangwon.tistory.com/16

**Comment by hpk23** [comment]
위 사이트를 참고해서 했더니 파일이 제대로 받아진것 같은데 서로 해시값이 다르게 나타나네요

**Comment by hpk23** [comment]
다른 파일들은 정상적으로 해시값 잘 나오고
binary file의 경우에만 해당하는것 같네요
